### ISSUE TITLE
mercadopago.getPaymentMethods error

### ISSUE THREAD

**Issue by gadfaria** [charleskx/mercadopago-v2-react#2]
First of all, your project is very cool!

Just one detail that happened to me, I was testing it and in the mercadopago.getPaymentMethods function, I was getting an incorrect parameters error, from what I could see, it seems that I need to pass the public_key as bearer token too, did this happen to you?

To solve this I replaced the mercadopago function for a fetch  
```
        const response = await fetch(
          https://api.mercadopago.com/v1/payment_methods/search?${queryString.stringify(
            { public_key: publicKey, bins: cardFirstSixDigit }
          )}`,
          {
            headers: {
              Authorization: `Bearer ${publicKey}
            },
          }
        );

        const { results }: GetPaymentMethods = await response.json();

        const paymentMethods = results[0];
```

**Comment by charleskx** [comment]
Did you follow the example file? Because that example works perfectly, I had no problems using it that way.

**Comment by gadfaria** [comment]
I found the problem haha
For some reason my test key is giving me error, with the production key it is going smoothly

Thanks for the attention

**Comment by charleskx** [comment]
> I found the problem haha For some reason my test key is giving me error, with the production key it is going smoothly
> 
> Thanks for the attention

HAHA HA
I found it strange, because I used exactly this package in the project at the college where I work and it worked 100%.

For nothing, I'm always available for whatever you need and if you want to contribute to the project, you're welcome.
